services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\Module\Authorizing\:
        resource: '../..'
        exclude:
            - '../../Application/*/*Command.php'
            - '../../Application/*/*Query.php'
            - '../../Application/*/*Result.php'
            - '../../Application/*/*Input.php'
            - '../../Application/*/*Event.php'
            - '../../Domain/'
            - '../../Infrastructure/Event/'
            - '../../Resources/'

    App\Module\Authorizing\Domain\AssignmentRepository:
        alias: App\Module\Authorizing\Infrastructure\Persistence\DoctrineAssignmentRepository

    App\Module\Authorizing\Domain\AuthorizationCatalog: ~
