monolog:
    channels: [deprecation]
    handlers:
        main:
            type: stream
            path: php://stderr
            level: warning
            formatter: monolog.formatter.json
            channels: ['!doctrine']
