framework:
    validation:
        mapping:
            paths:
                - '%kernel.project_dir%/src/Module/Authenticating/Resources/config/validation.yaml'
                - '%kernel.project_dir%/src/Module/TaskTracking/Resources/config/validation.yaml'

when@test:
    framework:
        validation:
            not_compromised_password: false
