<?php

declare(strict_types=1);

namespace App\Platform\Messaging\Resources\migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260912010000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create the Platform-owned Doctrine transport table for durable_events and durable_failed.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE public.platform_messaging_message (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX platform_messaging_message_queue_idx ON public.platform_messaging_message (queue_name, available_at, delivered_at, id)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE public.platform_messaging_message');
    }
}
