services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\Module\TaskTracking\:
        resource: '../..'
        exclude:
            - '../../Application/*/*Command.php'
            - '../../Application/*/*Query.php'
            - '../../Application/*/*Result.php'
            - '../../Application/*/*Input.php'
            - '../../Application/*/*Event.php'
            - '../../Domain/'
            - '../../Infrastructure/Event/'
            - '../../Resources/'

    App\Module\TaskTracking\Domain\TaskRepository:
        alias: App\Module\TaskTracking\Infrastructure\Persistence\DoctrineTaskRepository
